# docker-compose.yml
version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: railtime
    ports:
      - "51213:5432"
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg:
